import { useMemo, useState, type ChangeEvent } from 'react'
import { AlertTriangle, BrainCircuit, Building2, CheckCircle2, CreditCard, FileUp, RefreshCw, RotateCcw, ShieldCheck, Unplug, WalletCards } from 'lucide-react'
import { applySyncPreview, buildSyncPreview, consentDaysRemaining, disconnectConnector, startConnector, synchronizeConnections, type ConnectorConnection, type ConnectorProvider, type SyncPreview } from './connectors'
import { applyStatementImport, buildStatementPreview, parseStatement, type StatementPreview } from './statementImport'
import { getSecureValue, setSecureValue } from './vault'
import type { AppState } from './types'

interface ConnectionsPanelProps { state: AppState; onApply: (state: AppState) => void }
const BACKEND_URL_KEY = 'connector-backend-url'
const providers: Array<{ id: ConnectorProvider; title: string; description: string; icon: typeof Building2 }> = [
  { id: 'gocardless', title: 'Bankkonto (PSD2)', description: 'EU-Bankkonten über einen zugelassenen Kontoinformationsdienst verbinden.', icon: Building2 },
  { id: 'finapi', title: 'finAPI', description: 'Alternative deutsche Banking-Anbindung für produktive B2B-Integrationen.', icon: WalletCards },
  { id: 'paypal', title: 'PayPal', description: 'PayPal-Business-Transaktionen über die offizielle Reporting API synchronisieren.', icon: CreditCard },
]

export function ConnectionsPanel({ state, onApply }: ConnectionsPanelProps) {
  const [backendUrl, setBackendUrl] = useState(() => getSecureValue(BACKEND_URL_KEY, ''))
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('')
  const [connections, setConnections] = useState<ConnectorConnection[]>([])
  const [previews, setPreviews] = useState<SyncPreview[]>([]); const [statementPreview, setStatementPreview] = useState<StatementPreview | null>(null); const [rollbackState, setRollbackState] = useState<AppState | null>(null)
  const summary = useMemo(() => previews.reduce((result, preview) => ({
    accounts: result.accounts + preview.accountsToCreate.length,
    transactions: result.transactions + preview.transactionsToImport.length,
    duplicates: result.duplicates + preview.duplicateCount,
    pending: result.pending + preview.pendingCount,
    smartCategorized: result.smartCategorized + preview.quality.smartCategorized,
    needsReview: result.needsReview + preview.quality.needsReview,
    qualityTotal: result.qualityTotal + preview.quality.score,
  }), { accounts: 0, transactions: 0, duplicates: 0, pending: 0, smartCategorized: 0, needsReview: 0, qualityTotal: 0 }), [previews])
  const averageQuality = previews.length ? Math.round(summary.qualityTotal / previews.length) : 0
  const qualityWarnings = [...new Set(previews.flatMap((preview) => preview.quality.warnings))]

  const requireBackend = (): string => { const trimmed = backendUrl.trim().replace(/\/$/, ''); if (!/^https:\/\//.test(trimmed) && !/^http:\/\/localhost(?::\d+)?$/.test(trimmed)) throw new Error('Bitte eine HTTPS-Backend-Adresse oder localhost für die Entwicklung eintragen.'); setSecureValue(BACKEND_URL_KEY, trimmed); return trimmed }
  const connect = async (provider: ConnectorProvider) => { setBusy(true); setError(''); setMessage(''); try { await startConnector(provider, requireBackend()) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Verbindung konnte nicht gestartet werden.'); setBusy(false) } }
  const synchronize = async () => { setBusy(true); setError(''); setMessage(''); setPreviews([]); try { const payloads = await synchronizeConnections(requireBackend()); setConnections(payloads.map((payload) => payload.connection)); const successful = payloads.filter((payload) => payload.connection.status !== 'error'); const next = successful.map((payload) => buildSyncPreview(state, payload)); setPreviews(next); const failed = payloads.filter((payload) => payload.connection.status === 'error'); setMessage(next.length ? `Synchronisierung abgeschlossen. ${failed.length ? `${failed.length} Verbindung(en) benötigen Aufmerksamkeit. ` : ''}Prüfe Datenqualität und Vorschau vor dem Import.` : failed.length ? 'Keine Verbindung konnte erfolgreich synchronisiert werden.' : 'Keine aktiven Verbindungen gefunden.') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Synchronisierung fehlgeschlagen.') } finally { setBusy(false) } }
  const disconnect = async (provider: ConnectorProvider) => { if (!window.confirm('Diese Verbindung wirklich trennen? Bereits importierte Buchungen bleiben erhalten.')) return; setBusy(true); setError(''); try { await disconnectConnector(provider, requireBackend()); setConnections((current) => current.filter((connection) => connection.provider !== provider)); setMessage('Verbindung wurde sicher getrennt. Provider-Tokens wurden serverseitig entfernt.') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Verbindung konnte nicht getrennt werden.') } finally { setBusy(false) } }
  const importPreview = () => { setRollbackState(state); onApply(previews.reduce((current, preview) => applySyncPreview(current, preview), state)); setPreviews([]); setMessage(`${summary.transactions} Transaktionen und ${summary.accounts} Konten wurden importiert.`) }
  const readStatement = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; setError(''); setMessage(''); setStatementPreview(null); try { if (file.size > 5 * 1024 * 1024) throw new Error('Die Datei ist größer als 5 MB.'); const parsed = parseStatement(await file.text(), file.name); setStatementPreview(buildStatementPreview(state, parsed)); setMessage(`${parsed.rows.length} Buchungen aus ${file.name} gelesen. Prüfe die Vorschau.`) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Kontoauszug konnte nicht gelesen werden.') } }
  const importStatement = () => { if (!statementPreview) return; setRollbackState(state); onApply(applyStatementImport(state, statementPreview)); setMessage(`${statementPreview.transactions.length} Buchungen importiert; ${statementPreview.duplicates} Duplikate übersprungen.`); setStatementPreview(null) }
  const rollback = () => { if (!rollbackState) return; onApply(rollbackState); setRollbackState(null); setMessage('Der letzte Import wurde vollständig zurückgesetzt.') }

  return <div className="connections-page">
    <section className="panel assistant-hero"><div><p className="eyebrow">Automatische Finanzen</p><h2>Banken und PayPal verbinden</h2><p>Online-Banking-Passwörter und Provider-Secrets bleiben außerhalb des Browsers. Finanzregeln werden durch den COBOL-Kern validiert.</p></div><ShieldCheck size={32}/></section>
    <section className="panel connector-config"><label>Connector-Backend<input value={backendUrl} onChange={(event) => setBackendUrl(event.target.value)} placeholder="https://finance-api.example.de" inputMode="url" autoCapitalize="none" autoCorrect="off" spellCheck={false}/></label><button className="primary" disabled={busy} onClick={synchronize}><RefreshCw size={17}/>{busy ? 'Synchronisiere …' : 'Alle Verbindungen synchronisieren'}</button><p className="muted">Client-Secrets, Refresh-Tokens und PSD2-Zertifikate gehören ausschließlich in den Server oder einen Secret Manager.</p></section>
    {connections.length > 0 && <section className="panel"><div className="panel-header"><div><p className="eyebrow">Verbindungszustand</p><h2>Aktive Provider</h2></div><ShieldCheck size={24}/></div><div className="connection-health-list">{connections.map((connection) => { const days = consentDaysRemaining(connection); return <div className="account-row" key={connection.provider}><div className="account-icon">{connection.status === 'error' || (days !== null && days <= 7) ? <AlertTriangle size={19}/> : <CheckCircle2 size={19}/>}</div><div><strong>{connection.displayName}</strong><span>{connection.status === 'error' ? connection.error || 'Synchronisierung fehlgeschlagen' : connection.lastSyncAt ? `Zuletzt synchronisiert: ${new Date(connection.lastSyncAt).toLocaleString('de-DE')}` : 'Verbunden'}{days !== null ? ` · Zustimmung ${days < 0 ? 'abgelaufen' : `noch ${days} Tage gültig`}` : ''}</span></div><button className="secondary" disabled={busy} onClick={() => disconnect(connection.provider)}><Unplug size={16}/> Trennen</button></div> })}</div></section>}
    <section className="connector-grid">{providers.map((provider) => { const Icon = provider.icon; const connection = connections.find((item) => item.provider === provider.id); return <article className="panel connector-card" key={provider.id}><div className="goal-hero-icon"><Icon size={24}/></div><p className="eyebrow">Offizieller Connector</p><h2>{provider.title}</h2><span>{provider.description}</span><button className="secondary data-action" disabled={busy || connection?.status === 'connected'} onClick={() => connect(provider.id)}>{connection?.status === 'connected' ? 'Verbunden' : 'Verbinden'}</button></article> })}</section>
    <section className="panel statement-import"><div><p className="eyebrow">Fallback und Migration</p><h2>CSV- oder CAMT-Kontoauszug importieren</h2><p className="muted">Unterstützt deutsche CSV-Formate sowie CAMT.052, CAMT.053 und CAMT.054. Beträge werden als ganzzahlige Euro-Cent verarbeitet.</p></div><label className="secondary file-button"><FileUp size={17}/>Datei auswählen<input type="file" accept=".csv,.xml,.camt,text/csv,application/xml,text/xml" onChange={readStatement}/></label></section>
    {statementPreview && <section className="panel sync-preview"><div className="panel-header"><div><p className="eyebrow">Auszugsvorschau</p><h2>{statementPreview.account.name}</h2></div><CheckCircle2 size={24}/></div><div className="stats-grid compact"><article className="stat-card"><span>Buchungen</span><strong>{statementPreview.transactions.length}</strong></article><article className="stat-card"><span>Duplikate</span><strong>{statementPreview.duplicates}</strong></article><article className="stat-card"><span>Fehlerhafte Zeilen</span><strong>{statementPreview.rejected}</strong></article><article className="stat-card"><span>Format</span><strong>{statementPreview.format.toUpperCase()}</strong></article></div><button className="primary" disabled={!statementPreview.transactions.length} onClick={importStatement}>Geprüfte Buchungen importieren</button></section>}
    {previews.length > 0 && <section className="panel sync-preview"><div className="panel-header"><div><p className="eyebrow">KI-gestützte Importvorschau</p><h2>Bankdaten-Qualität: {averageQuality}%</h2></div><BrainCircuit size={24}/></div><div className="stats-grid compact"><article className="stat-card"><span>Neue Konten</span><strong>{summary.accounts}</strong></article><article className="stat-card"><span>Neue Buchungen</span><strong>{summary.transactions}</strong></article><article className="stat-card"><span>Smart kategorisiert</span><strong>{summary.smartCategorized}</strong></article><article className="stat-card"><span>Prüfung nötig</span><strong>{summary.needsReview}</strong></article></div><p className="muted">Vorgemerkte Buchungen werden nicht importiert. Duplikate werden über externe IDs und Inhaltsfingerprints erkannt. Kategorien werden nur aus wiederholter, konsistenter Händlerhistorie übernommen.</p>{qualityWarnings.length > 0 && <div className="privacy-box"><ShieldCheck size={17}/><span>{qualityWarnings.join(' ')}</span></div>}<button className="primary" onClick={importPreview}>Geprüfte Daten importieren</button></section>}
    {rollbackState && <button className="secondary rollback-button" onClick={rollback}><RotateCcw size={17}/>Letzten Import zurücksetzen</button>}
    {message && <p className="status-message success-message" role="status">{message}</p>}{error && <p className="status-message error-message" role="alert">{error}</p>}
  </div>
}
